name: Publish Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish (cli, runner-node, or all)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - cli
          - runner-node

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Publish @envguard/cli to npm
        if: github.event.inputs.package == 'all' || github.event.inputs.package == 'cli' || github.event_name == 'release'
        working-directory: ./packages/cli
        run: pnpm publish --no-git-checks --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

      - name: Publish @envguard/runner-node to npm
        if: github.event.inputs.package == 'all' || github.event.inputs.package == 'runner-node' || github.event_name == 'release'
        working-directory: ./packages/runner-node
        run: pnpm publish --no-git-checks --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

      # Optional: Also publish to GitHub Packages
      - name: Setup Node.js for GitHub Packages
        if: github.event_name == 'release'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@envguard'

      - name: Publish @envguard/cli to GitHub Packages
        if: github.event_name == 'release'
        working-directory: ./packages/cli
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Publish @envguard/runner-node to GitHub Packages
        if: github.event_name == 'release'
        working-directory: ./packages/runner-node
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
